### ISSUE TITLE
Add marshalling of return event type

### ISSUE THREAD

**Issue by danbev** [boson-project/faas-js-runtime#31]
Currently, if a user want to send a CloudEvent repsonse back to the Knative broker they have to set the HTTP headers manually. This could instead be handled by the runtime.

**Comment by lance** [comment]
@danbev any time/interest in coding a spike for this?

**Comment by danbev** [comment]
@lance Yeah, I'll try to give this a shot next week.

**Comment by lance** [comment]
@danbev are you satisfied that [this PR](https://github.com/boson-project/faas-js-runtime/pull/34) should resolve the issue?

**Comment by danbev** [comment]
@lance Yeah, I think it is. I'll update the knative eventing demo with this also.
